// @temporal-cortex/toon — WASM-powered TOON encoder/decoder for Node.js
//
// This module loads the WASM binary compiled from the toon-wasm Rust crate.
// The WASM bindings are generated by wasm-bindgen as CommonJS (.cjs), but this
// package uses ESM ("type": "module" in package.json). We bridge the two module
// systems using Node's createRequire().
//
// Build chain: toon-core (Rust) → toon-wasm (wasm-bindgen) → toon-js (this wrapper)

import { createRequire } from "module";
const require = createRequire(import.meta.url);

// Load the WASM-generated Node.js bindings (.cjs for CommonJS/ESM compat)
const wasm = require("../wasm/toon_wasm.cjs") as {
  encode: (json: string) => string;
  decode: (toon: string) => string;
};

/**
 * Encode a JSON string into TOON format.
 * @param json - A valid JSON string
 * @returns The TOON-encoded string
 */
export function encode(json: string): string {
  return wasm.encode(json);
}

/**
 * Decode a TOON string back into JSON format.
 * @param toon - A valid TOON string
 * @returns The JSON string
 */
export function decode(toon: string): string {
  return wasm.decode(toon);
}
