// @temporal-cortex/truth-engine — WASM-powered RRULE expansion, conflict
// detection, and free/busy computation for Node.js.
//
// This module loads the WASM binary compiled from the truth-engine-wasm Rust
// crate. The WASM bindings are generated by wasm-bindgen as CommonJS (.cjs),
// but this package uses ESM ("type": "module" in package.json). We bridge the
// two module systems using Node's createRequire().
//
// Build chain:
//   truth-engine (Rust) -> truth-engine-wasm (wasm-bindgen) -> truth-engine-js (this wrapper)

import { createRequire } from "module";
const require = createRequire(import.meta.url);

// Load the WASM-generated Node.js bindings (.cjs for CommonJS/ESM compat)
const wasm = require("../wasm/truth_engine_wasm.cjs") as {
  expandRRule: (
    rrule: string,
    dtstart: string,
    duration_minutes: number,
    timezone: string,
    until?: string,
    max_count?: number,
  ) => string;
  findConflicts: (events_a_json: string, events_b_json: string) => string;
  findFreeSlots: (events_json: string, window_start: string, window_end: string) => string;
};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface TimeRange {
  start: string;
  end: string;
}

export interface Conflict {
  event_a: TimeRange;
  event_b: TimeRange;
  overlap_minutes: number;
}

export interface FreeSlot {
  start: string;
  end: string;
  duration_minutes: number;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Expand an RFC 5545 RRULE into concrete event instances.
 *
 * @param rrule - RFC 5545 recurrence rule (e.g., "FREQ=DAILY;COUNT=3")
 * @param dtstart - Local datetime for the first occurrence (e.g., "2026-02-17T14:00:00")
 * @param durationMinutes - Duration of each instance in minutes
 * @param timezone - IANA timezone (e.g., "America/Los_Angeles")
 * @param until - Optional end boundary (local datetime string)
 * @param maxCount - Optional maximum number of instances to generate
 * @returns Array of {start, end} objects with RFC 3339 datetime strings
 */
export function expandRRule(
  rrule: string,
  dtstart: string,
  durationMinutes: number,
  timezone: string,
  until?: string,
  maxCount?: number,
): TimeRange[] {
  const json = wasm.expandRRule(
    rrule,
    dtstart,
    durationMinutes,
    timezone,
    until ?? undefined,
    maxCount ?? undefined,
  );
  return JSON.parse(json);
}

/**
 * Find all pairwise conflicts (overlapping time ranges) between two event lists.
 *
 * @param eventsA - First list of events
 * @param eventsB - Second list of events
 * @returns Array of conflict objects with event_a, event_b, and overlap_minutes
 */
export function findConflicts(
  eventsA: TimeRange[],
  eventsB: TimeRange[],
): Conflict[] {
  const json = wasm.findConflicts(JSON.stringify(eventsA), JSON.stringify(eventsB));
  return JSON.parse(json);
}

/**
 * Find free time slots within a given window, given a list of busy events.
 *
 * @param events - List of busy events
 * @param windowStart - Start of the search window (ISO 8601 datetime)
 * @param windowEnd - End of the search window (ISO 8601 datetime)
 * @returns Array of free slot objects with start, end, and duration_minutes
 */
export function findFreeSlots(
  events: TimeRange[],
  windowStart: string,
  windowEnd: string,
): FreeSlot[] {
  const json = wasm.findFreeSlots(JSON.stringify(events), windowStart, windowEnd);
  return JSON.parse(json);
}
